#remote_theme: pages-themes/midnight@v0.2.0
plugins:
#  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - ei-in-port-programs.md
  - gen-event-demystified.md
  - non-blocking-tcp-server.md
  - snmp-quick-start.md
